name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw -B clean install --file pom.xml

    - name: Diagnostic des Secrets
      run: |
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then echo "❌ USERNAME est VIDE"; else echo "✅ USERNAME est détecté"; fi
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "❌ TOKEN est VIDE"; else echo "✅ TOKEN est détecté"; fi

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gestionschool:latest
